/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Business.EmployeeWorkArea;

import Business.Department.Department;
import Business.Department.Department.DepartmentType;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Stephanie
 */
public class ServiceWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Department department;
    private UserAccount userAccount;
    private Enterprise enterprise;

    
    public ServiceWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise,Department department,UserAccount userAccount) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        valueLabel.setText(userAccount.getDepartmentType().toString());
        this.department = department;
        populateTable();
        switch (userAccount.getDepartmentType())
        {
            case CINEMA_TICKET:
                btnReceive.setVisible(false);
                break;
            case CINEMA_FOOD:
                btnReceive.setVisible(false);
                break;
            case CINEMA_SERVICE:
                btnReceive.setVisible(false);
                break;
            case ANALYTICS_USER:
            case ANALYTICS_MOVIE:
                btnSend.setVisible(false);
                break;
                
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valueLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWorkRequest = new javax.swing.JTable();
        btnReceive = new javax.swing.JButton();
        btnSend = new javax.swing.JButton();
        btnMy = new javax.swing.JButton();

        valueLabel.setText("<value>");

        tblWorkRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Receiver", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblWorkRequest);

        btnReceive.setText("Receive Request");
        btnReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceiveActionPerformed(evt);
            }
        });

        btnSend.setText("Send Request");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        btnMy.setText("My Request");
        btnMy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 615, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnReceive)
                        .addGap(58, 58, 58)
                        .addComponent(btnSend)
                        .addGap(55, 55, 55)
                        .addComponent(btnMy)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReceive)
                    .addComponent(btnSend)
                    .addComponent(btnMy))
                .addGap(71, 71, 71))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblWorkRequest.getModel();
        model.setRowCount(0); 
        for (WorkRequest request : department.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[4];
            String temp[] = request.getMessage().split(",");
            row[0] = temp[1];
            row[1] = request.getSender()==null?null:request.getSender().getEmployee().getName();
            row[2] = request.getReceiver()==null?null:request.getReceiver().getEmployee().getName();
            row[3] = request;
            model.addRow(row);
        }
    }

    private void btnReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceiveActionPerformed
         int row = tblWorkRequest.getSelectedRow();
        if(row < 0)
        {
            JOptionPane.showMessageDialog(null, "Please select any row!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
       WorkRequest request = (WorkRequest)tblWorkRequest.getValueAt(row, 3);
       if(request.getReceiver()!=null&&!userAccount.getDepartmentType().equals(DepartmentType.SUPPLIER_TRANSPORTATION))
       {
           JOptionPane.showMessageDialog(null, "This request has benn received by another user", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
       }
       request.setReceiver(userAccount);
       switch (userAccount.getDepartmentType())
        {
           case SUPPLIER_TRANSPORTATION:
               request.setStatus("Shipped");
               break;
           default:
               request.setStatus("Processing");
               break;    
       }
       userAccount.getWorkQueue().getWorkRequestList().add(request);
       JOptionPane.showMessageDialog(null, "Received Successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
       populateTable();
    }//GEN-LAST:event_btnReceiveActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        CardLayout crdLyt;
        switch (userAccount.getDepartmentType())
        {
            case CINEMA_SERVICE:
            case CINEMA_TICKET:
                userProcessContainer.add("TicketRequestJPanel", new MovieRequestJPanel(userProcessContainer, enterprise,department, userAccount));
                crdLyt = (CardLayout) userProcessContainer.getLayout();
                crdLyt.next(userProcessContainer);
                break;
      
            case CINEMA_FOOD:
                userProcessContainer.add("FoodRequestJPanel", new FoodRequestJPanel(userProcessContainer, department, userAccount));
                crdLyt = (CardLayout) userProcessContainer.getLayout();
                crdLyt.next(userProcessContainer);
                break;
            case SUPPLIER_TRANSPORTATION:
                if(userAccount.getWorkQueue().getWorkRequestList().size()==0)
                {
                     JOptionPane.showMessageDialog(null, "Please receive a task first", "Information", JOptionPane.INFORMATION_MESSAGE);
                return;
                }
            case SUPPLIER_SERVICE:
                userProcessContainer.add("ViewMyTaskJPanel", new ViewMyTaskJPanel(userProcessContainer, enterprise,userAccount));
                crdLyt = (CardLayout) userProcessContainer.getLayout();
                crdLyt.next(userProcessContainer);
                break;
                    
        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnMyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyActionPerformed
        // TODO add your handling code here:
         CardLayout crdLyt;
        switch (userAccount.getDepartmentType())
        {
         case SUPPLIER_SERVICE:
             userProcessContainer.add("ViewMyTaskJPanel", new ViewMyTaskJPanel(userProcessContainer,enterprise,userAccount));
         crdLyt = (CardLayout) userProcessContainer.getLayout();
        crdLyt.next(userProcessContainer);
             break;
         default:
             userProcessContainer.add("ViewMyTaskJPanel", new ViewMyTaskJPanel(userProcessContainer,null,userAccount));
         crdLyt = (CardLayout) userProcessContainer.getLayout();
        crdLyt.next(userProcessContainer);
             break;
        }
         
    }//GEN-LAST:event_btnMyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMy;
    private javax.swing.JButton btnReceive;
    private javax.swing.JButton btnSend;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblWorkRequest;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
