/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Business.Graphic;

import Business.Analytics.DataAnalytic;
import Business.Enterprise.Cinema;
import Business.Test.RandomData;
import java.awt.CardLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import javax.imageio.ImageIO;
import javax.swing.JPanel;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;

/**
 *
 * @author sdzh4
 */
public class DisplayJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayJPanel
     */
    private Image image;
    private String Imgpath="chart.jpg";
//    private JFreeChart chart;
    private JPanel userProcessContainer;
    public DisplayJPanel(JPanel userProcessContainer,String Imgpath) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.Imgpath= Imgpath;
        
//        this.chart = chart;
//        Map<Integer,Double> sale = new HashMap<>();
//        Map<Integer,String> category = new HashMap<>();
//        sale.put(0, 5.0);
//        sale.put(1, 7.0);
//        sale.put(2, 9.0);
//        category.put(0, "test1");
//        category.put(1, "test2");
//        category.put(2, "test3");
//        PaintPieChart ppc = new PaintPieChart();
       // JFreeChart chart = ppc.PaintChart("test",null,null,sale,category);
       
       //Data generator
//       RandomData generator = new RandomData();
//       generator.addRandomData();
//       DataAnalytic testanalytic= new DataAnalytic();
//      Map<Integer,Double> movieperformance =  testanalytic.toMap_performence(generator.getPerformance());
//       Map<Integer,String> movie = new HashMap<>();
//       movie.put(0, "food-1");
//       movie.put(1, "food-2");
//       movie.put(2, "food-3");
//       movie.put(3, "food-4");
//       movie.put(4, "food-5");
//       movie.put(5, "food-6");
//       movie.put(6, "food-7");
//       movie.put(7, "food-8");
//       movie.put(8, "food-9");
//       movie.put(9, "food-10");
//       movie.put(10, "food-11");
//       movie.put(11, "food-12");
//       movie.put(12, "food-13");
//       movie.put(13, "food-14");
//       movie.put(14, "food-15");
//       movie.put(15, "food-16");
//       movie.put(16, "food-17");
//       movie.put(17, "food-18");
//       movie.put(18, "food-19");
//       movie.put(19, "food-20");
////       PaintPieChart ppc = new PaintPieChart();
////        chart = ppc.PaintChart("foodtest",null,null,movieperformance,movie);
//       PaintBarChart pbc = new PaintBarChart();
//       chart = pbc.PaintChart("movietest","movie","performance",movieperformance,movie);
//       
//       writeImg(chart);
        readImg(Imgpath);
    }
    
    
    public void writeImg(JFreeChart chart)
    {
         try { 
            FileOutputStream chartjpg = null; 
            chartjpg = new FileOutputStream(Imgpath); 
            ChartUtilities.writeChartAsJPEG(chartjpg,1.0f,chart,1680, 1050,null);  //change width and height
            chartjpg.close();
        } 
        catch (FileNotFoundException e)
        {
            e.printStackTrace();  
        }
        catch(IOException e)
        {
            e.printStackTrace();  
        }
    }
    
     public void readImg(String imgPath) {  
        try {  
            image = ImageIO.read(new FileInputStream(imgPath));  
        } catch (FileNotFoundException e) {  
            e.printStackTrace();  
        } catch (IOException e) {  
            e.printStackTrace();  
        }  
    } 
    @Override
 public void paintComponent(Graphics g1) {  
        int x = 0;  
        int y = 0;  
        Graphics g = (Graphics) g1;  
        if (null == image) {  
            return;  
        }  
       g.drawImage(image, 0,0, image.getWidth(this), image.getHeight(this),this);  
        g = null;  
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(1560, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(973, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
